redox-os/kernel

src/lib.rs

Otherwise, compilation fails with:
```
Compiling kernel v0.1.0 (file:///home/corentih/rust/redox/kernel)
error: unused `#[macro_use]` import
--> kernel/src/lib.rs:40:1
|
40 | #[macro_use]
| ^^^^^^^^^^^^
|
note: lint level defined here
--> kernel/src/lib.rs:6:9
|
6  | #![deny(warnings)]
|         ^^^^^^^^
error: aborting due to previous error
error: Could not compile `kernel`.
```

remove unused #[macro_use]

---

Cargo.toml
build.rs
src/scheme/initfs.rs

Kernel should be decoupled and can be compiled on it's own.
initfs folder should be specified in INITFS_FOLDER environment variable.
Corresponding PR will be sent to redox repo in few seconds
Please be patient, I am Rust begginer :)

Remove hardcoded initfs folder

---

arch/x86_64/Cargo.toml

A kernel panic occurs on some CPUs (notably qemu-system-x86_64) when
calling rust-cpuid's get_extended_function_info.  This is fixed upstream
in commit c3ebfc553cdff98d19d29777fd85c4f9182bfb66 but has yet to make
it crates.io.
The panic can by triggered by running "ls sys:" from ion and causes
redox to become unresponsive.

Prevent cpuid get_extended_function_info panic

---

arch/x86_64/src/acpi/mod.rs
arch/x86_64/src/device/mod.rs
arch/x86_64/src/device/rtc.rs
arch/x86_64/src/start.rs

The ACPI code now saves the FADT in a globally accessible mutex, with infrastructure in place to add additional tables to the mutex if necessary.
The x86_64 device initialization has been split into "core" devices necessary for initialization, and "non-core" devices not necessary to bring the kernel up, which are initialized, respectively, before and after ACPI.
The RTC read function now checks for the presence of the FADT, and, if present, uses the century register indicated in the table. If not present, it defaults to assuming the 21st century as before.

Implemented reading from RTC Century counter in x86_64 arch, if available

---

build.rs

There was a bug at the `initfs` generation which made the listing of the contents of the `initfs:`subdirectories impossible from the command line.
The subdirectory listing data had the full paths of the files (like `bin/ahcid\nbin/bgad\n...`) when it should just only be the names of the files (`ahcid\nbgad\n...`)

Fix the listing of `initfs:` directories

---

src/externs.rs

The default implementation of the memcpy, memmove, memset and 
memcmp functions in the kernel file `extern.rs` uses a naive implementation
by copying, assigning or comparing bytes ony by one. This can be slow.
This commit proposes a reimplementation of those functions by copying,
assigning or comparing in group of 8 bytes by using the u64 type and
its respective pointers instead of u8. Alternative version for 32-bit
architectures are also supplied for future compatibility with x86.
Both version first copy whatever they can with wide word types. The
tail, i.e. the final few bytes that do not fit in a dword or qword
are then copied byte by byte.
A comparison of performance of all functions on both 32-bit and 64-bit version 
can be seen in commit …

A faster implementation of the memcpy family

---

src/context/switch.rs
src/interrupt/irq.rs

PIT interrupt should context switch or else all of Redox crashes.
This will fix programs like the Snake game crashing all of Redox.
A global AtomicUSize counter was added, and a line to switch contexts
on every 10 PIT interrupts in irq.rs.
This fixes https://github.com/redox-os/redox/issues/781 (Snake Game crashes Redox #781) (Tested)

Fix PIT Interrupt Not Context Switching [irq]

---

src/scheme/env.rs

This also requires a small modification to libstd; I guess I'll submit a PR to redox-os/rust, and if it looks okay a PR can be sent upstream as well. Everything has to be rebuilt for this change, if it sets environmental variables. That seems unavoidable though.
Hopefully this is okay, but I don't know why that if condition was commented out, so perhaps it causes issues I'm not aware of.

Make env: return ENOENT on non-existent; support unlink()

---

src/syscall/mod.rs
src/syscall/process.rs

Requires https://github.com/redox-os/syscall/pull/10

Implement getppid system call

---

src/syscall/process.rs

I don't know if this was there for a reason, but it was making the dup() fail with tcpd, and I don't seem this being handled specially in redoxfs or anywhere else.
This seems to have been the cause for one issue I was having with `git`; it was somewhat cryptic since the actual call that was failing (the dup itself) wasn't listed in the log of the program's system calls, and I think earlier I missed the fact that the failing read was in another process that had forked.

Pass empty second argument to dup() call in clone

---

src/scheme/pipe.rs

Oops, this was incorrect. The `weak_count` test handles this, and this change causes it to return EOF when any file descriptor is dropped, if there are several.
The real cause of the issue I had was because it failed to set `O_CLOEXEC` with `fcntl()`, which wasn't clear because it didn't make any system call (since that function wasn't implemented in newlib) and git wasn't checking the return value. That is addressed in https://github.com/redox-os/newlib/pull/40.

Revert "pipe: make read() return when write end is closed"

---

src/syscall/process.rs

Autotools configure scripts seem to use "#! /bin/sh"

Strip whitspaces after #!

---

src/syscall/fs.rs

The code I was dealing with for some reason closed the second file descriptor before dup2, but that should be valid.
The `?` here may be accidental, given the `let _ =`.

Make dup2() work if second file descriptor doesn't exist

---

src/context/context.rs

Fixes strange behavior like 'cd .//////; pwd'

Strip extra slashes from path

---

src/context/context.rs
src/context/file.rs
src/scheme/sys/iostat.rs
src/syscall/fs.rs
src/syscall/process.rs

This maintains dup with a second meaning when the second argument is non-empty. It may be worth changing that API, but it is not handled in this PR.
This also adds `F_SETFD` and `F_GETFD` to fcntl.
Depends on https://github.com/redox-os/syscall/pull/16.

Use file descriptions, shared between file descriptors

---

src/externs.rs

I'm not entirely sure about it, but the rest of the file treats 32 bits as groups of 4 so it makes sense that memcpy does the same.

Correct small bug in memcpy 32bits implementation

---

src/externs.rs
src/lib.rs

Since `core::mem::size_of` is constant function there is no need for them to be duplicated.

 Deduplicate memcpy, memmove, memset and memcmp functions

---

src/lib.rs
src/scheme/mod.rs
src/syscall/privilege.rs

This implements capability mode similar to [`cap_enter` on `FreeBSD`](https://www.freebsd.org/cgi/man.cgi?query=cap_enter&sektion=2), by introducing a null scheme namespace.
Entering this namespace removes any ability to `open`, `unlink`, `chown`, `chmod`, or `exec`, meaning that security properties of a process are easier to determine.

Capability mode support using null namespace

---

Cargo.lock
Cargo.toml
src/acpi/dmar/mod.rs
src/acpi/hpet.rs
src/acpi/madt.rs
src/acpi/mod.rs
src/acpi/rsdp.rs
src/arch/x86_64/device/local_apic.rs
src/arch/x86_64/idt.rs
src/arch/x86_64/paging/entry.rs
src/arch/x86_64/paging/mapper.rs
src/arch/x86_64/paging/mod.rs
src/arch/x86_64/paging/table.rs
src/arch/x86_64/start.rs
src/context/memory.rs
src/devices/uart_16550.rs
src/scheme/user.rs
src/syscall/driver.rs
src/syscall/process.rs
src/syscall/validate.rs

This pull request updates the `bitflags` crate to version 1.
The major change is that `bitflags` now uses associated constants, so the uses of the various constants had to be prefixed with the `bitflags` structure.

Update to `bitflags` version 1.0

---

linkers/x86_64.ld

Do not discard the .debug section. If the builder would like to discard
this section, they can do so explicitly with objcopy.

Do not discard .debug section

---

src/arch/x86_64/paging/entry.rs
src/arch/x86_64/paging/mapper.rs
src/arch/x86_64/paging/table.rs

Use unused bits 51-61 in first entries of each page table as a counter for used entries.
I also removed unnecessary checks in unmap_inner.
After this change checking if page table is empty is a O(1) operation instead of O(N), where N is the number of entries.

Page table optimization

---

src/arch/x86_64/device/hpet.rs
src/arch/x86_64/device/mod.rs

The HPET specification says you must set TN_VAL_SET_CNF in order to set a periodic timer's accumulator, but doesn't say what happens to the timer's interval in that case.  This has led to a few different interpretations:
* In [Qemu](https://github.com/qemu/qemu/blob/v2.2.1/hw/timer/hpet.c#L534), [Bochs](https://github.com/svn2github/bochs/blob/master/bochs/iodev/hpet.cc#L515), and probably most real hardware, the written value falls through and sets both the acccumulator and the interval.
* In [VirtualBox](https://github.com/mdaniel/virtualbox-org-svn-vbox-trunk/blob/master/src/VBox/Devices/PC/DevHPET.cpp#L558) both are set regardless of whether TN_VAL_SET_CNF is set.
* In [Xen](https://github.com/mirage/xen/blob/master/xen/arch/x86/hvm/hpet.c#L423) and on [some real …

Write hpet timer twice

---

Cargo.toml
alloc_kernel/Cargo.toml
src/arch/x86_64/start.rs
src/lib.rs
src/memory/mod.rs
src/memory/slab.rs

Changes current linked list allocator for slab allocator.
Allocations <= 4096 bytes are made in fixed size blocks, >4096 bytes use current allocator.
Here are the benchmark results:
```
test allocate_many_small_blocks_linked_list            ... bench:   8,904,698 ns/iter (+/- 523,010)
test allocate_many_small_blocks_slab                   ... bench:   2,884,013 ns/iter (+/- 120,920)
test allocate_multiple_sizes_linked_list_over_4096     ... bench:       2,151 ns/iter (+/- 166)
test allocate_multiple_sizes_linked_list_up_to_4096    ... bench:      23,771 ns/iter (+/- 1,712)
test allocate_multiple_sizes_linked_list_various_sizes ... bench:       7,120 ns/iter (+/- 606)
test allocate_multiple_sizes_slab_over_4096            ... bench:       2,240 ns/iter (+/- 83)
test …
```

Use slab allocator for kernel heap

---

src/syscall/process.rs

Tests process existence, but does not send a signal. Matches POSIX behavior.

kill: support signal number 0

---

src/arch/x86_64/stop.rs

Cause interrupt, since the IDT is dorked we can't find the INT 3
handler (double fault), and the double fault handler can't be
found (triple fault).

Fix TODO: Use triple fault to guarantee reboot
